### ISSUE TITLE
running on mac, gulp build not working

### ISSUE THREAD

**Issue by rednaxus** [mcasimir/generator-mobileangularui#4] opened 2014-10-22 18:16 UTC
Hi, 

I'm trying this and it doesn't do as advertised, I type:
yo mobileangularui
gulp build
and I get:
'mobile-angular-ui/src/less/mobile-angular-ui.less' wasn't found in file /Users/me/dev/workspace/phonegap/weather/src/less/app.less line no. 1

the process does not put mobile-angular-ui into the project root, should it?

**Comment by PaoloMessina** [comment] 2015-01-19 10:19
Hi All, 
i find the same error!
i'm working with generator v1.3.3

C:\Users\XXX\hybridApp\MobAngUI>gulp build
[11:09:56] Using gulpfile ~\hybridApp\MobAngUI\gulpfile.js
[11:09:56] Starting 'build'...
[11:09:56] Starting 'clean'...
[11:09:56] Finished 'clean' after 17 ms
[11:09:56] Starting 'html'...
[11:09:56] Finished 'html' after 1.67 ms
[11:09:56] Starting 'fonts'...
[11:09:56] Starting 'images'...
[11:09:56] Starting 'less'...
[11:09:56] Finished 'less' after 4.88 ms
[11:09:56] Starting 'js'...
[11:09:56] Finished 'js' after 19 ms
[11:09:56] Finished 'fonts' after 32 ms
[11:09:56] gulp-imagemin: Minified 0 images (saved 0 B - 0%)
[11:09:56] Finished 'images' after 33 ms
[11:09:56] Finished 'build' after 57 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: 'mobile-angular-ui/src/less/mobile-angular-ui.less' wasn't found in file
C:\Users\XXX\hybridApp\MobAngUI\src\less\app.less line no. 1

I can't apply the wa by @sl45sms because i can't find the file overlay.less
I can see only this files under the less folder:

app.less
mixins.less
responsive.less
variables.less

An the variables.less file is empty.

**Comment by mcasimir** [comment] 2015-01-19 11:53
@PaoloMessina could you report the output of `ls bower_contents` and `ls bower_contents/mobile-angular-ui/src/less`?

The other error `@zindex-modal-background is undefined`: is caused mobile-angular-ui and twitter bootstrap are out of sync. Updating mobile-angular-ui in bower.json should fix it.

Another quick fix is to define the variable somewhere:

Ie. in `variables.less`:

``` css
@zindex-modal-background: 1000;
```

**Comment by brainjay** [comment] 2015-01-23 10:00
I've got an error:

[10:57:42] Using gulpfile ~\test\gulpfile.js
[10:57:42] Starting 'default'...
[10:57:42] Starting 'build'...
[10:57:42] Starting 'clean'...
[10:57:42] Finished 'clean' after 20 ms
[10:57:42] Starting 'html'...
[10:57:42] Finished 'html' after 1.97 ms
[10:57:42] Starting 'fonts'...
[10:57:42] Starting 'images'...
[10:57:42] Starting 'less'...
[10:57:42] Finished 'less' after 4.77 ms
[10:57:42] Starting 'js'...
[10:57:42] Finished 'js' after 13 ms
[10:57:42] gulp-imagemin: Minified 0 images (saved 0 B - 0%)
[10:57:42] Finished 'images' after 30 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: 'font-awesome/less/spinning.less' wasn't found in file C:\Users\XXX\test\bower_components\mobile-angular-ui\src\less\mobile-angular-ui.less line no. 18

dir bower_components
23.01.2015  10:54    <DIR>          .
23.01.2015  10:54    <DIR>          ..
23.01.2015  10:54    <DIR>          angular
23.01.2015  10:54    <DIR>          angular-route
23.01.2015  10:54    <DIR>          bootstrap
23.01.2015  10:54    <DIR>          font-awesome
23.01.2015  10:54    <DIR>          jquery
23.01.2015  10:54    <DIR>          mobile-angular-ui

dir \mobile-angular-ui\src\less\
23.01.2015  10:54    <DIR>          .
23.01.2015  10:54    <DIR>          ..
23.01.2015  10:54    <DIR>          lib
23.01.2015  10:54    <DIR>          migrate
23.01.2015  10:54                96 migrate.less
23.01.2015  10:54             2.324 mobile-angular-ui-desktop.less
23.01.2015  10:54             2.863 mobile-angular-ui.less
23.01.2015  10:54               757 sm-grid.less
23.01.2015  10:54             3.199 variables.less

**Comment by dragonito** [comment] 2015-01-23 21:42
Just comment out or delete:
@import "font-awesome/less/spinning";

**Comment by PipStyles** [comment] 2015-01-28 14:08
@dragonito Yes, this has fixed it for me also. bower_components/font-awesome/less/spinning is indeed missing now.

Very odd error and the error "reporting" from gulp-less is opaque in the extreme. Certainly needs a fix.

**Comment by RemcovandenBerg** [comment] 2015-04-19 19:35
The issue is already resolved with (mcasimir/mobile-angular-ui#226).

**Closed by RemcovandenBerg** 2015-04-19 19:35 UTC
