### ISSUE TITLE
error on lib\less\parser.js:333:27

### ISSUE THREAD

**Issue by alzalabany** [mcasimir/generator-mobileangularui#14] opened 2015-03-23 13:17 UTC
i followed guid to start a new project.

phonegap create ui
cd ui
yo mobileangularui

all went smooth, then when i run, it give me this error.

<pre>
E:\xampp\htdocs\si\ui>gulp build
[15:06:41] Using gulpfile E:\xampp\htdocs\si\ui\gulpfile.js
[15:06:41] Starting 'build'...
[15:06:41] Starting 'clean'...
[15:06:41] Finished 'clean' after 39 ms
[15:06:41] Starting 'html'...
[15:06:41] Finished 'html' after 2.57 ms
[15:06:41] Starting 'fonts'...
[15:06:41] Starting 'images'...
[15:06:41] Starting 'less'...
[15:06:41] Finished 'less' after 6.27 ms
[15:06:41] Starting 'js'...
[15:06:41] Finished 'js' after 19 ms
[15:06:41] gulp-imagemin: Minified 0 images (saved 0 B - 0%)
[15:06:41] Finished 'images' after 44 ms

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error
    at new Parser (E:\xampp\htdocs\si\ui\node_modules\gulp-less\node_modules\les
s\lib\less\parser.js:333:27)
    at Object.less.render (E:\xampp\htdocs\si\ui\node_modules\gulp-less\node_mod
ules\less\lib\less\index.js:18:22)
    at Transform._transform (E:\xampp\htdocs\si\ui\node_modules\gulp-less\index.
js:38:10)
    at Transform._read (E:\xampp\htdocs\si\ui\node_modules\gulp-less\node_module
s\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (E:\xampp\htdocs\si\ui\node_modules\gulp-less\node_modul
es\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (E:\xampp\htdocs\si\ui\node_modules\gulp-less\node_modules\throug
h2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (E:\xampp\htdocs\si\ui\node_modules\gulp-less\node_modules\
through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at Transform.Writable.write (E:\xampp\htdocs\si\ui\node_modules\gulp-less\no
de_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)

    at write (E:\xampp\htdocs\si\ui\node_modules\gulp\node_modules\vinyl-fs\node
_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (E:\xampp\htdocs\si\ui\node_modules\gulp\node_modules\vinyl-fs\node_
modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)

E:\xampp\htdocs\si\ui>yo mobileangularui --version
1.4.6
</pre>

**Comment by pranaysharmadelhi** [comment] 2015-04-18 14:46
+1 on Windows

**Comment by RemcovandenBerg** [comment] 2015-04-19 19:28
The issue is already resolved with (mcasimir/mobile-angular-ui#226).
The quickest way is to adjust your 'bower.json' file, change ` "font-awesome": "4.x",` to   `"font-awesome": "4.2",`
Or get the latest version from np by uninstalling and installing generator-mobileangularui

**Closed by RemcovandenBerg** 2015-04-19 19:28 UTC
